#!/bin/bash
## settings...
DOT_FILES=".bash_itrc .bash_profile .bashrc .inputrc .tmux.conf .vimrc .ssh/."
BREW_PROGRAMS="gcc wget vim tmux n python ruby git ssh-copy-id"

## settings end

RED='\033[0;31m'
NC='\033[0m' # No Color
SCRIPT_PATH="`dirname \"$0\"`"

# abort on error
set -e

if [ "$1" == "--dry-run" ]; then
  echo "Dry run mode..."; echo
  DRY_RUN=1
fi

function run {
  echo "  > $1"
  if [ -z "$DRY_RUN" ]; then
    eval $1
  fi
}

function find_command {
  command -v git >/dev/null 2>&1 || { echo >&2 "git is required for this installation but it's not installed.  Aborting."; exit 1; }
  echo `command -v $1`
}

# check if git is installed
git_command=`find_command git`
# check if curl is installed
curl_command=`find_command curl`
# check if ruby is installed
ruby_command=`find_command ruby`

# install linuxbrew
echo "# Installing linuxbrew"
brew_install="printf '\n' | ${ruby_command} -e \"\`curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install\`\""
run "$brew_install"
PATH="$HOME/.linuxbrew/bin:$PATH"
brew_command=`which brew`
run "$brew_command update"

for pname in $BREW_PROGRAMS; do
  run "${brew_command} install ${pname}"
done

# install node with n
echo "# Installing node with n"
run "sudo -k chown -R $USER /usr/local/"
run "n lts"
run "n stable"

# install bash_it
echo "# Installing Bash-it"
bash_it_git="Bash-it/bash-it"
bash_it_location="${HOME}/.bash_it"
bash_it_clone="$git_command clone --depth=1 https://github.com/$bash_it_git.git ${bash_it_location}"
bash_it_install="${HOME}/.bash_it/install.sh --silent"
run "rm -rf ${bash_it_location}"
run "$bash_it_clone"
run "$bash_it_install"

# copy dot files
for filename in $DOT_FILES; do
  echo "# Copying ${filename}"
  from_file="${SCRIPT_PATH}/${filename}"
  to_file="${HOME}/${filename}"
  copy_file="cp -a ${from_file} ${to_file}"
  backup_file="cp -a ${to_file} ${to_file}.backup"
  if [ -f "${to_file}" ]; then
    run "$backup_file"
  fi
  run "$copy_file"
  echo
done

# vim plug
echo "# Installing vim plug"
vim_plug="$curl_command -fLo ${HOME}/.vim/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
run "$vim_plug"
run "vim +PlugInstall +qall"
echo

# cleaning up
echo -e "\n${RED}Please relogin to see changes.${NC}"
